### ISSUE TITLE
Boda-rtc

### ISSUE THREAD

**Issue by bhack** [naibaf7/libdnn#16]
Just to be aware of https://arxiv.org/abs/1606.00094 /cc @moskewcz

**Comment by bhack** [comment]
I add also an interesting [Input Space Splitting for Opencl](http://compilers.cs.uni-saarland.de/papers/moll_pollocl.pdf)

**Comment by moskewcz** [comment]
FWIW, i am here lurking about. it's not much mentioned in that paper, but Boda-rtc also targets NVidia (using both/either CUDA and OpenCL), where i get similar (~cuDNN v2-v3 range) perf for the conv cases i targeted (alexnet/NiN/googlenetV1). Using OpenCL or CUDA doesn't make much/any difference for me -- the post-OpenCL/CUDA 'binary' (ptx) in both flows is almost the same, as one might hope/expect. also, in the past i did some minor experiments targeting AMD (on a pre-fiji card), and plan to do more with a more recent card (R9 Nano is on order).

**Comment by bhack** [comment]
Have you experimented with winograd kernels?

**Comment by moskewcz** [comment]
nope, but it's certainly on my wish list and i'd argue/hope it should fit well in the framework. in general i'm currently pretty time limited wrt to adding features/completeness: part time trying to finish phd, part time work.

**Comment by bhack** [comment]
@hughperkins Started a [Opencl porting](https://github.com/hughperkins/neonCl-underconstruction) of some neon winogard kernels if you are interested.

**Comment by moskewcz** [comment]
thanks for the heads-up.

**Comment by hughperkins** [comment]
Interesting paper :-)

**Comment by hughperkins** [comment]
Whoa, blast from the past :O

**Comment by moskewcz** [comment]
yep. on a related note: i did finally graduate somehow!

mwm

**Comment by hughperkins** [comment]
Nice :) Tesla sounds cool :)
