### ISSUE TITLE
Question about the generated OpenCL convolution kernels

### ISSUE THREAD

**Issue by romix** [naibaf7/libdnn#26]
I'm trying to use LibDNN generated kernels instead of my own naive kernel below:

```c++
struct NCHW {
   size_t n;
   size_t c;
   size_t h;
   size_t w;
};

inline size_t getNCHWIndex(NCHW s, size_t n, size_t c, size_t h,
               size_t w) {
  return (n * s.c * s.w * s.h) + (c * s.h * s.w) + (h * s.w) + w;
}

/// Perform a convolution on the inputs in NCHW format.
__kernel 
void oclconvolutionK(
                                     __global float *dest,
                                     __global float *src,
                                     __global float *filter,
                                     __global float *bias,
                                     unsigned filterSize,
                                     unsigned stride,
                                     unsigned pad, 
                                     NCHW destDim, NCHW srcDim,
                                     NCHW filterDim) {
  // dest x
  size_t ax = get_global_id(0);
  // dest y
  size_t ay = get_global_id(1);
  // dest channel
  size_t d = get_global_id(2);

  typedef int ssize_t;
  ssize_t x = -(ssize_t)pad + ax * stride;
  ssize_t y = -(ssize_t)pad + ay * stride;

  // For each input in the batch:
  for (size_t n = 0; n < srcDim.n; n++) {
    // For each element in the convolution-filter:
    float sum = 0;
    for (size_t fx = 0; fx < filterSize; fx++) {
      for (size_t fy = 0; fy < filterSize; fy++) {
        ssize_t ox = x + fx;
        ssize_t oy = y + fy;

        // Ignore index access below zero (this is due to padding).
        if (ox < 0 || oy < 0 || ox >= (ssize_t)srcDim.h ||
            oy >= (ssize_t)srcDim.w) {
          continue;
        }

        for (size_t fd = 0; fd < srcDim.c; fd++) {
          sum += filter[getNCHWIndex(filterDim, d, fd, fx, fy)] *
                 src[getNCHWIndex(srcDim, n, fd, (size_t)ox, (size_t)oy)];
        }
      }
    }

    sum += bias[d];
    dest[getNCHWIndex(destDim, n, d, ax, ay)] = sum;
  } // N
}
```

I checked that my kernel generates correct results.

But I get rather different results from the libDNN generated kernels, if the filter (i.e. kernel) size is > 1. 
I guess I'm doing something wrong. 

So, I'd like to check with you if at least at the logical level the kernels generated by libDNN are computing mathematically the same convolution or may be you use a slightly different formula?

**Comment by naibaf7** [comment]
Do you have a minimal working example with a small kernel and simple reproducible input that you can compute by hand as well? Just by looking at the code now I can't see any obvious mistakes.
LibDNN is verified (inside Caffe) against CuDNN and im2col+gemm convolutions. Have you checked the filter dimensions etc.? Are they the same for both implementations?

**Comment by romix** [comment]
Yes, I've no doubts that LibDnn generates correct kernels. I bet I do something wrong when I configure or invoke them. But I could not find yet what is wrong.

This is how I configure and invoke libDnn. It seems correct to me:

```c++
  typedef float Dtype;
  ...
  LibDNNConvConfig config;
  config.dev_ptr = devPtr;
  // NCHW is the expected format of input and output.
  config.in_shape = std::vector<int_tp>{in_n, in_c, in_h, in_w};
  config.out_shape = std::vector<int_tp>(out_n, out_c, out_h, out_w);
  // The expected format for kernel, pad and stride is HxW.
  config.kernel = std::vector<int_tp>{filterSize, filterSize};
  config.pad = std::vector<int_tp>{pad, pad};
  config.stride = std::vector<int_tp>{stride, stride};
  config.dilation = std::vector<int_tp>{0, 0};
  config.group = 1;
  config.bias_term = true;
  config.fast_unsafe_math = true;
  config.weights_backward = false;
  config.bias_backward = false;
  config.wgalgo = LIBDNN_CONVOLUTION_WG_ALGO_DIRECT;
  LibDNNConv<Dtype> *libdnn = new LibDNNConv<Dtype>(config);
  ...
  /// Invoke the generated convolution kernel.
  libdnn->Forward((float *)inputBuf, (float *)filterBuf, (float *)biasBuf, (float *)outputBuf, 1);
```

**Comment by romix** [comment]
> LibDNN is verified (inside Caffe) against CuDNN and im2col+gemm convolutions.

Just to be on the safe-side: There were no bugs in the libDNN implementation that got fixed inside the Caffe version of libDNN but never ported back to the standalone libDNN?

**Comment by romix** [comment]
BTW, I test it on resnet50.

**Comment by naibaf7** [comment]
Use a simpler test than a fully fledged CNN to check for correctness. i.e. a 5x5 image with numbers from 1.0 to 25.0 and a simple 3x3 kernel.
From your code it's looking like if your filter dimension is the same. For Caffe/LibDNN that would be:
`[conv_out_channels, conv_in_channels/groups, H, W]`, just to re-check.
Another thing: the standard dilation is supposed to be `{1, 1}`, not `{0, 0}`, meaning the filter should move on 1 coordinate in each spatial dimension (dense). For `{2, 2}`, a 3x3 dense filter would become a 5x5 sparse filter.
Generally, stride is default 1, dilation default 1 and padding defaults to 0.

Furthermore you should be aware that the LibDNN is lagging behind LibDNN in Caffe in terms of features. Correctness should still be given, but for example quantization, deconvolution, pooling (partially) and support for mobile devices is still absent in standalone.

**Comment by romix** [comment]
My filter dimensions are:  `[conv_out_channels, conv_in_channels, H, W]`. 
where `conv_out_channels ` is `out_c` and `conv_in_channels` is `in_c`. `H` and `W` are both `filterSize`.
`in_n` and `out_n` are the batch sizes, which is 1 in my tests.


What is the meaning of`groups` in libDNN?

**Comment by naibaf7** [comment]
So it could really be the dilation parameter that's wrong in your LibDNN usage.

Groups does the following:
Given a convolution with 32 input feature maps, and 128 output feature maps, that would usually be 4096 filters. Now with grouping, that convolution can be split up into e.g. two convolutions of 16 input and 64 output feature maps each, reducing the number of parameters to 2x(16x64)=2048 instead. That would be groups=2, but an arbitrary number that divides both input and output channels can be chosen.
It basically allows to have larger numbers of feature maps while keeping parameters and cost of computation low.

**Comment by romix** [comment]
Thanks for the explanation about `groups`.

As for `dilation`, I tried with `[0, 0]` and `[1, 1]`. But IMHO, `[0, 0]` is the value that should be used for CNNs like resnet50, unless I'm totally wrong.

One other thing which I don't understand and find very strange: 

When I print the values, the `output` of the convolution produced by libDNN on my inputs does not only differ from the output produced by the kernel above, but it looks like all values for the `output[conv_out_c][conv_out_c][h][w]` are the same if we fix conv_out_c and conv_out_c when printing and loop only over h and w.

We get something like this (old is the results produced by my kernel above and new are the results produced by libDNN with the config above).

```
Convolution results differ at index (0, 0, 0, 0) :new = 2.429369e+00 vs old = 2.129374e+00
Convolution results differ at index (0, 0, 0, 1) :new = 2.429369e+00 vs old = 1.922677e+00
Convolution results differ at index (0, 0, 0, 2) :new = 2.429369e+00 vs old = 1.912586e+00
Convolution results differ at index (0, 0, 1, 0) :new = 2.429369e+00 vs old = 2.493358e+00
Convolution results differ at index (0, 0, 1, 1) :new = 2.429369e+00 vs old = 2.064355e+00
Convolution results differ at index (0, 0, 1, 2) :new = 2.429369e+00 vs old = 1.918630e+00
Convolution results differ at index (0, 0, 2, 0) :new = 2.429369e+00 vs old = 2.447888e+00
Convolution results differ at index (0, 0, 2, 1) :new = 2.429369e+00 vs old = 2.138869e+00
Convolution results differ at index (0, 0, 2, 2) :new = 2.429369e+00 vs old = 2.006434e+00
Convolution results differ at index (0, 1, 0, 0) :new = 4.363781e-01 vs old = 5.926343e-01
Convolution results differ at index (0, 1, 0, 1) :new = 4.363781e-01 vs old = 5.845606e-01
Convolution results differ at index (0, 1, 0, 2) :new = 4.363781e-01 vs old = 5.850284e-01
Convolution results differ at index (0, 1, 1, 0) :new = 4.363781e-01 vs old = 4.685953e-01
Convolution results differ at index (0, 1, 1, 1) :new = 4.363781e-01 vs old = 5.725086e-01
Convolution results differ at index (0, 1, 1, 2) :new = 4.363781e-01 vs old = 6.076341e-01
Convolution results differ at index (0, 1, 2, 0) :new = 4.363781e-01 vs old = 5.591991e-01
Convolution results differ at index (0, 1, 2, 1) :new = 4.363781e-01 vs old = 6.383934e-01
Convolution results differ at index (0, 1, 2, 2) :new = 4.363781e-01 vs old = 6.659725e-01
Convolution results differ at index (0, 2, 0, 0) :new = 3.819129e+00 vs old = -4.105482e-01
Convolution results differ at index (0, 2, 0, 1) :new = 3.819129e+00 vs old = -1.263880e+00
Convolution results differ at index (0, 2, 0, 2) :new = 3.819129e+00 vs old = -1.196164e+00
Convolution results differ at index (0, 2, 1, 0) :new = 3.819129e+00 vs old = -1.133431e+00
Convolution results differ at index (0, 2, 1, 1) :new = 3.819129e+00 vs old = -1.889593e+00
Convolution results differ at index (0, 2, 1, 2) :new = 3.819129e+00 vs old = -1.829563e+00
Convolution results differ at index (0, 2, 2, 0) :new = 3.819129e+00 vs old = -1.027151e+00
Convolution results differ at index (0, 2, 2, 1) :new = 3.819129e+00 vs old = -1.708840e+00
Convolution results differ at index (0, 2, 2, 2) :new = 3.819129e+00 vs old = -1.674557e+00
```

**Comment by naibaf7** [comment]
Dilation [0, 0] does not exist in LibDNN. The minimum is [1, 1] (which is dense convolution, or normal). Other frameworks may handle this differently though. In Caffe, dilation is handled like stride (with 1 as the default). So please try [1, 1] again on the dilation.
What GPU are you testing on?

**Comment by romix** [comment]
Sorry, you are absolutely right! The setting for dilation was wrong! I'm getting correct results now!
